### ISSUE TITLE
Error when VCF sort for huge file

### ISSUE THREAD

**Issue by antonylebechec** [bioinfo-chru-strasbourg/howard#218]
When generating dbNSFP ALL VCF, error append due to huge data. 
Add memory limit (increase) to solve the issue.

> Error:
```
[E::hts_open_format] Failed to open file "/Users/lebechea/howard/databases/dbnsfp/current/hg19/dbNSFP4.4a.ALL.vcf.gz.641.tmpqhH2Dk/00218.bcf" : Too many open files
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/HOWARD/howard/functions/commons.py", line 2013, in concat_and_compress_files
    pysam.bcftools.sort(
  File "/usr/local/Caskroom/miniconda/base/envs/howard_devel/lib/python3.10/site-packages/pysam/utils.py", line 83, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'bcftools returned with error -1: stdout=None, stderr=Writing to /Users/lebechea/howard/databases/dbnsfp/current/hg19/dbNSFP4.4a.ALL.vcf.gz.641.tmpqhH2Dk\nMerging 228 temporary files\nCould not read /Users/lebechea/howard/databases/dbnsfp/current/hg19/dbNSFP4.4a.ALL.vcf.gz.641.tmpqhH2Dk/00218.bcf: Too many open files\nCleaning\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/howard_devel/bin/howard", line 33, in <module>
    sys.exit(load_entry_point('howard', 'console_scripts', 'howard')())
  File "/Users/lebechea/BIOINFO/git/HOWARD/howard/main.py", line 273, in main
    eval(f"{command_function}(args)")
  File "<string>", line 1, in <module>
  File "/Users/lebechea/BIOINFO/git/HOWARD/howard/tools/databases.py", line 272, in databases
    databases_download_dbnsfp(
  File "/Users/lebechea/BIOINFO/git/HOWARD/howard/functions/databases.py", line 2690, in databases_download_dbnsfp
    index=True,
  File "/Users/lebechea/BIOINFO/git/HOWARD/howard/functions/commons.py", line 2026, in concat_and_compress_files
    raise ValueError(f"Output file sorting failed: {output_file_tmp}")
ValueError: Output file sorting failed: /Users/lebechea/howard/databases/dbnsfp/current/hg19/dbNSFP4.4a.ALL.vcf.gz.641.tmp
```

**Comment by antonylebechec** [comment]
done.
